### ISSUE TITLE
Crash during setup process

### ISSUE THREAD

**Issue by Skeeww** [herrnst/HuaweiMatebookD14AMD-OpenCore#4]
Hello,

I just run the installer for Mac OS Ventura, I disabled NootedRed then booted to Mac OS in order to complete the setup.

It showed me the country/region selection but right after hitting the next button, I ended up with a gray screen then a couple of minutes after a popup "Setup Assistant quit unexpectedly" then a few more minutes later my computer restart.

I don't know how to fix this issue or even debug it

Thanks in advance

**Comment by herrnst** [comment]
Sorry, I probably cannot really help with that. Back then (it's been quite some time since I installed Ventura on the D14 AMD) I had to disable NootedRed for all setup purposes (first installation, OS updates etc) but never ran into any issues with that. Since some time and quite a few NootedRed updates ago, it isn't even necessary to disable NootedRed at all anymore.

I also cannot say how to retrieve debug information from the installer, guess it's best to seek for generic macOS Installation troubleshooting in this case to find out what causes troubles, and then determine if the issue is something machine specific, or maybe something with the installer (corrupt media or so) or firmware settings, although there's not much to break with the default UEFI setup of the D14 AMD unless you're messing with things like Smokeless_UMAF.
